name: n
on:
 workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: 
         sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/xlabr/u/sh/qk2.sh)"
         mv /usr/local/etc/trojan/config.json /temp/
         mv /etc/nginx/sites-available/default /temp/
    
      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: test
          tag_name: test
          draft: false
          prerelease: false
          files: |
            /tmp/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
