name: t
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "NAME=trojan" >> $GITHUB_ENV
          echo "TMPDIR=$(mktemp -d)" >> $GITHUB_ENV
          echo "VERSION=$(curl -fsSL https://api.github.com/repos/trojan-gfw/trojan/releases/latest | grep tag_name | sed -E 's/.*"v(.*)".*/\1/')" >> $GITHUB_ENV          
        
      - name: Tar
        run: |
          TARBALL="$NAME-$VERSION-linux-amd64.tar.xz"
          DOWNLOADURL="https://github.com/trojan-gfw/$NAME/releases/download/v$VERSION/$TARBALL"     
          cd "$TMPDIR"           
          curl -LO --progress-bar "$DOWNLOADURL" || wget -q --show-progress "$DOWNLOADURL" 
          tar xf "$TARBALL"          
          mv trojan /tmp           
          cd /tmp
          mv trojan/examples/* trojan  
          
      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            /tmp/trojan/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
